[package]
name = "catsay_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.15.11"

[dependencies.gtk]
version = "0.15.5"
features = ["v3_24"]